// ======================================================
// BLL_OBSERVACION.GS
// Reglas de observaciones: validación, alta, edición y baja lógica.
// ======================================================
class BLL_Observacion {
  static registrar(datos,confirmado,deps=null,ahora=new Date()){
    deps=deps||{supervisiones:DAL_Supervision,tipificaciones:DAL_Tipificacion,observaciones:DAL_Observacion}; exigir(confirmado,"OBS_NO_CONFIRMADA","Debe confirmar la observación."); const rs=deps.supervisiones.buscarPorObra(datos.codigoObra); exigir(rs,"SUPERVISION_NO_EXISTE","No existe supervisión."); const s=MAP_Supervision.FilaaBE(rs.datos); exigir(s.Estado===Config.ESTADOS_SUPERVISION.EN_CURSO,"SUPERVISION_FINALIZADA","La supervisión está finalizada."); const rt=deps.tipificaciones.buscarPorId(datos.idTipificacion); exigir(rt,"TIPIFICACION_NO_EXISTE","Tipificación inexistente."); const t=MAP_Tipificacion.FilaaBE(rt.datos); exigir(t.EstadoTipificacion==="ACTIVA","TIPIFICACION_INACTIVA","La tipificación no está activa.");
    const tieneCoord=datos.latitud!==null&&datos.latitud!==undefined&&datos.longitud!==null&&datos.longitud!==undefined; exigir(tieneCoord||String(datos.referenciaUbicacion||"").trim(),"UBICACION_REQUERIDA","Debe indicar ubicación o referencia."); if(String(t.Descripcion).toUpperCase()==="OTROS") exigir(String(datos.comentario||"").trim(),"COMENTARIO_REQUERIDO","OTROS requiere comentario.");
    const id=datos.idObservacion||this._nuevoId(deps.observaciones,ahora); const o=new BE_Observacion(id,datos.codigoObra,datos.codUsuario,datos.idTipificacion,ahora,datos.latitud??null,datos.longitud??null,datos.referenciaUbicacion||"",datos.comentario||""); deps.observaciones.insertar(MAP_Observacion.BEaFila(o)); return o;
  }
  static editar(id,cambios,codUsuario,deps=null,ahora=new Date()){deps=deps||{supervisiones:DAL_Supervision,observaciones:DAL_Observacion};const r=deps.observaciones.buscarPorId(id);exigir(r,"OBS_NO_EXISTE","Observación inexistente.");const o=MAP_Observacion.FilaaBE(r.datos);const rs=deps.supervisiones.buscarPorObra(o.CodigoObra);exigir(rs&&MAP_Supervision.FilaaBE(rs.datos).Estado===Config.ESTADOS_SUPERVISION.EN_CURSO,"SUPERVISION_FINALIZADA","No se puede editar una supervisión finalizada.");exigir(o.Estado===Config.ESTADOS_REGISTRO.ACTIVA,"OBS_ELIMINADA","La observación está eliminada.");["IdTipificacion","Latitud","Longitud","ReferenciaUbicacion","Comentario"].forEach(k=>{if(cambios[k]!==undefined)o[k]=cambios[k];});o.FechaUltModificacion=ahora;o.CodUsuarioUltModificacion=codUsuario;deps.observaciones.actualizar(r.fila,MAP_Observacion.BEaFila(o));return o;}
  static eliminar(id,codUsuario,deps=null,ahora=new Date()){deps=deps||{supervisiones:DAL_Supervision,observaciones:DAL_Observacion};const r=deps.observaciones.buscarPorId(id);exigir(r,"OBS_NO_EXISTE","Observación inexistente.");const o=MAP_Observacion.FilaaBE(r.datos);const rs=deps.supervisiones.buscarPorObra(o.CodigoObra);exigir(rs&&MAP_Supervision.FilaaBE(rs.datos).Estado===Config.ESTADOS_SUPERVISION.EN_CURSO,"SUPERVISION_FINALIZADA","No se puede eliminar una supervisión finalizada.");exigir(o.Estado===Config.ESTADOS_REGISTRO.ACTIVA,"OBS_ELIMINADA","La observación ya está eliminada.");o.Estado=Config.ESTADOS_REGISTRO.ELIMINADA;o.FechaEliminacion=ahora;o.CodUsuarioEliminacion=codUsuario;deps.observaciones.actualizar(r.fila,MAP_Observacion.BEaFila(o));return o;}
  static listarActivas(codigoObra,repo=null){repo=repo||DAL_Observacion;return repo.listarPorObra(codigoObra,true).map(r=>MAP_Observacion.FilaaBE(r.datos));}
  static _nuevoId(repo,ahora){const base=Utilities.formatDate(ahora,Session.getScriptTimeZone()||"GMT","yyyyMMddHHmmss");let n=1;const ids=repo.listar().map(f=>String(f[0]));while(ids.includes(`OBS${base}${String(n).padStart(3,"0")}`))n++;return `OBS${base}${String(n).padStart(3,"0")}`;}
}
