// ======================================================
// QA_CU00.JS
// Regresión automática de reglas críticas de usuarios.
// ======================================================
function QA_CU00(){const q=new QA_Runner("CU00");const t0=new Date("2026-08-01T12:00:00Z");const roles=new QA_RolRepo();
  q.caso("CU00-01","Alta válida queda pendiente",()=>{const r=new QA_Repo();const u=BLL_Usuario.solicitarAlta("1","Ana","Paz",Config.ROLES.SUPERVISOR,r,t0,roles);QA_Assert.igual(u.EstadoAprobacion,Config.ESTADOS_APROBACION.PENDIENTE);QA_Assert.igual(u.Activo,Config.ACTIVO.NO);});
  q.caso("CU00-02","No duplica Telegram ID",()=>{const r=new QA_Repo();BLL_Usuario.solicitarAlta("1","Ana","Paz",Config.ROLES.SUPERVISOR,r,t0,roles);QA_Assert.error(()=>BLL_Usuario.solicitarAlta("1","Ana","Paz",Config.ROLES.SUPERVISOR,r,t0,roles),"USUARIO_EXISTENTE");QA_Assert.igual(r.rows.length,1);});
  q.caso("CU00-03","Administrador no es rol público",()=>{const r=new QA_Repo();QA_Assert.error(()=>BLL_Usuario.solicitarAlta("1","Ana","Paz",Config.ROLES.ADMINISTRADOR,r,t0,roles),"ROL_NO_PERMITIDO");});
  q.caso("CU00-04","Rechazado puede volver a solicitar alta",()=>{const r=new QA_Repo();BLL_Usuario.solicitarAlta("1","Ana","Paz",Config.ROLES.SUPERVISOR,r,t0,roles);BLL_Usuario.rechazarUsuario("1","ADM001",r,t0);const u=BLL_Usuario.solicitarAlta("1","Ana","Paz",Config.ROLES.GERENTE,r,t0,roles);QA_Assert.igual(u.RolSolicitado,Config.ROLES.GERENTE);QA_Assert.igual(r.rows.length,1);});
  q.caso("CU00-05","Aprobación asigna rol y código",()=>{const r=new QA_Repo();BLL_Usuario.solicitarAlta("1","Ana","Paz",Config.ROLES.SUPERVISOR,r,t0,roles);const u=BLL_Usuario.aprobarUsuario("1","ADM001",r,t0,roles);QA_Assert.igual(u.CodUsuario,"SUP001");QA_Assert.igual(u.RolAprobado,Config.ROLES.SUPERVISOR);QA_Assert.igual(u.Activo,Config.ACTIVO.SI);});
  q.caso("CU00-06","Código de usuario es incremental por rol",()=>{const r=new QA_Repo();for(const id of ["1","2"]){BLL_Usuario.solicitarAlta(id,"A","B",Config.ROLES.SUPERVISOR,r,t0,roles);BLL_Usuario.aprobarUsuario(id,"ADM001",r,t0,roles);}QA_Assert.igual(MAP_Usuario.FilaaBE(r.rows[1]).CodUsuario,"SUP002");});
  q.caso("CU00-07","Pendiente no obtiene acceso",()=>{const r=new QA_Repo();BLL_Usuario.solicitarAlta("1","A","B",Config.ROLES.SUPERVISOR,r,t0,roles);QA_Assert.igual(BLL_Usuario.registrarAcceso("1",r,t0).estado,"PENDIENTE");});
  q.caso("CU00-08","Aprobado activo obtiene acceso",()=>{const r=new QA_Repo();BLL_Usuario.solicitarAlta("1","A","B",Config.ROLES.SUPERVISOR,r,t0,roles);BLL_Usuario.aprobarUsuario("1","ADM001",r,t0,roles);QA_Assert.igual(BLL_Usuario.registrarAcceso("1",r,new Date("2026-08-02T12:00:00Z")).estado,"ACCESO_OK");});
  q.caso("CU00-09","Inactividad genera reactivación",()=>{const r=new QA_Repo();BLL_Usuario.solicitarAlta("1","A","B",Config.ROLES.SUPERVISOR,r,t0,roles);BLL_Usuario.aprobarUsuario("1","ADM001",r,t0,roles);QA_Assert.igual(BLL_Usuario.registrarAcceso("1",r,new Date("2026-09-15T12:00:00Z")).estado,"PENDIENTE_REACTIVACION");});
  q.caso("CU00-10","Administrador no se inactiva",()=>{const r=new QA_Repo();r.insertar(MAP_Usuario.BEaFila(new BE_Usuario("9","Admin","Uno",Config.ROLES.ADMINISTRADOR,Config.ROLES.ADMINISTRADOR,"ADM001",Config.ESTADOS_APROBACION.APROBADO,Config.ACTIVO.SI,t0,t0,"ADM001",t0)));QA_Assert.igual(BLL_Usuario.registrarAcceso("9",r,new Date("2027-01-01T12:00:00Z")).estado,"ACCESO_OK");});
  q.caso("CU00-11","Reactivación conserva código y rol",()=>{const r=new QA_Repo();BLL_Usuario.solicitarAlta("1","A","B",Config.ROLES.SUPERVISOR,r,t0,roles);let u=BLL_Usuario.aprobarUsuario("1","ADM001",r,t0,roles);BLL_Usuario.registrarAcceso("1",r,new Date("2026-09-15T12:00:00Z"));u=BLL_Usuario.aprobarUsuario("1","ADM001",r,new Date("2026-09-16T12:00:00Z"),roles);QA_Assert.igual(u.CodUsuario,"SUP001");QA_Assert.igual(u.RolAprobado,Config.ROLES.SUPERVISOR);});
  q.caso("CU00-12","No registrado se identifica",()=>{QA_Assert.igual(BLL_Usuario.registrarAcceso("404",new QA_Repo(),t0).estado,"NO_REGISTRADO");});
  q.caso("CU00-13","Cambio manual a aprobado completa datos de aprobación",()=>{const r=new QA_Repo();BLL_Usuario.solicitarAlta("1","Ana","Paz",Config.ROLES.SUPERVISOR,r,t0,roles);r.rows[0][6]=Config.ESTADOS_APROBACION.APROBADO;const u=BLL_Usuario.aprobarDesdeEdicionManual("1",Config.ESTADOS_APROBACION.PENDIENTE,"ADM001",r,t0,roles);QA_Assert.igual(u.RolAprobado,Config.ROLES.SUPERVISOR);QA_Assert.igual(u.CodUsuario,"SUP001");QA_Assert.igual(u.Activo,Config.ACTIVO.SI);QA_Assert.igual(u.AprobadoPor,"ADM001");QA_Assert.igual(u.FechaAprobacion,t0);});
  q.caso("CU00-14","Aprobación manual no reprocesa usuario ya aprobado",()=>{const r=new QA_Repo();BLL_Usuario.solicitarAlta("1","Ana","Paz",Config.ROLES.SUPERVISOR,r,t0,roles);r.rows[0][6]=Config.ESTADOS_APROBACION.APROBADO;BLL_Usuario.aprobarDesdeEdicionManual("1",Config.ESTADOS_APROBACION.PENDIENTE,"ADM001",r,t0,roles);QA_Assert.error(()=>BLL_Usuario.aprobarDesdeEdicionManual("1",Config.ESTADOS_APROBACION.PENDIENTE,"ADM001",r,t0,roles),"USUARIO_YA_APROBADO");});
  return QA_imprimir(q.resumen());}
