// ======================================================
// QA_CU01.JS
// Regresión automática de reglas críticas de supervisión.
// ======================================================
function QA_CU01(){const q=new QA_Runner("CU01");const ahora=new Date("2026-08-20T10:00:00Z");
  const deps=()=>{const obras=new QA_Repo(),supervisiones=new QA_Repo(),tips=new QA_Repo(),obs=new QA_Repo();obras.insertar(MAP_Obra.BEaFila(new BE_Obra("AD566AF","CONT01",Config.FAMILIAS_OBRA.FTTH,Config.ACTIVO.SI)));tips.insertar(MAP_Tipificacion.BEaFila(new BE_Tipificacion("TIP001",Config.FAMILIAS_OBRA.FTTH,"GENERAL","CAJA MAL FIJADA","ALTA","ACTIVA")));tips.insertar(MAP_Tipificacion.BEaFila(new BE_Tipificacion("TIP999",Config.FAMILIAS_OBRA.FTTH,"GENERAL","OTROS","MEDIA","ACTIVA")));return{obras,supervisiones,tips,obs};};
  q.caso("CU01-01","Inicio requiere confirmación",()=>{const d=deps();QA_Assert.error(()=>BLL_Supervision.iniciar("AD566AF","SUP001",false,{obras:d.obras,supervisiones:d.supervisiones},ahora),"INICIO_NO_CONFIRMADO");QA_Assert.igual(d.supervisiones.rows.length,0);});
  q.caso("CU01-02","Inicio crea EN_CURSO con fecha y autor",()=>{const d=deps();const x=BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora).supervision;QA_Assert.igual(x.Estado,Config.ESTADOS_SUPERVISION.EN_CURSO);QA_Assert.igual(x.CodUsuarioInicio,"SUP001");});
  q.caso("CU01-03","No duplica supervisión EN_CURSO",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);const x=BLL_Supervision.iniciar("AD566AF","SUP002",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);QA_Assert.ok(x.existente);QA_Assert.igual(d.supervisiones.rows.length,1);});
  q.caso("CU01-04","No reinicia supervisión FINALIZADA",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);BLL_Supervision.finalizar("AD566AF","SUP001",true,d.supervisiones,ahora);QA_Assert.error(()=>BLL_Supervision.iniciar("AD566AF","SUP002",true,{obras:d.obras,supervisiones:d.supervisiones},ahora),"SUPERVISION_FINALIZADA");});
  q.caso("CU01-05","Finalización requiere confirmación",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);QA_Assert.error(()=>BLL_Supervision.finalizar("AD566AF","SUP001",false,d.supervisiones,ahora),"FINALIZACION_NO_CONFIRMADA");});
  q.caso("CU01-06","Puede finalizar con cero observaciones",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);const s=BLL_Supervision.finalizar("AD566AF","SUP001",true,d.supervisiones,ahora);QA_Assert.igual(s.Estado,Config.ESTADOS_SUPERVISION.FINALIZADA);});
  q.caso("CU01-07","Observación requiere confirmación",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);QA_Assert.error(()=>BLL_Observacion.registrar({codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP001",latitud:-34,longitud:-58},false,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora),"OBS_NO_CONFIRMADA");});
  q.caso("CU01-08","Observación requiere ubicación o referencia",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);QA_Assert.error(()=>BLL_Observacion.registrar({codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP001"},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora),"UBICACION_REQUERIDA");});
  q.caso("CU01-09","OTROS requiere comentario",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);QA_Assert.error(()=>BLL_Observacion.registrar({codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP999",latitud:-34,longitud:-58},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora),"COMENTARIO_REQUERIDO");});
  q.caso("CU01-10","Observación válida conserva autor",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);const o=BLL_Observacion.registrar({codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP001",latitud:-34,longitud:-58},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora);QA_Assert.igual(o.CodUsuario,"SUP001");});
  q.caso("CU01-11","Edición registra trazabilidad y conserva autor",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);const o=BLL_Observacion.registrar({idObservacion:"OBS1",codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP001",latitud:-34,longitud:-58},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora);const e=BLL_Observacion.editar(o.IdObservacion,{Comentario:"corregido"},"SUP002",{supervisiones:d.supervisiones,observaciones:d.obs},ahora);QA_Assert.igual(e.CodUsuario,"SUP001");QA_Assert.igual(e.CodUsuarioUltModificacion,"SUP002");});
  q.caso("CU01-12","Eliminación es lógica",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);const o=BLL_Observacion.registrar({idObservacion:"OBS1",codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP001",latitud:-34,longitud:-58},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora);const e=BLL_Observacion.eliminar(o.IdObservacion,"SUP002",{supervisiones:d.supervisiones,observaciones:d.obs},ahora);QA_Assert.igual(e.Estado,Config.ESTADOS_REGISTRO.ELIMINADA);QA_Assert.igual(d.obs.rows.length,1);});
  q.caso("CU01-13","Finalizada queda solo lectura",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);BLL_Observacion.registrar({idObservacion:"OBS1",codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP001",latitud:-34,longitud:-58},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora);BLL_Supervision.finalizar("AD566AF","SUP001",true,d.supervisiones,ahora);QA_Assert.error(()=>BLL_Observacion.editar("OBS1",{Comentario:"x"},"SUP001",{supervisiones:d.supervisiones,observaciones:d.obs},ahora),"SUPERVISION_FINALIZADA");});
  q.caso("CU01-14","Solo tipificación activa",()=>{const d=deps();d.tips.rows[0][5]="INACTIVA";BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);QA_Assert.error(()=>BLL_Observacion.registrar({codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP001",latitud:-34,longitud:-58},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora),"TIPIFICACION_INACTIVA");});
  q.caso("CU01-15","Edición OTROS mantiene comentario obligatorio",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);const o=BLL_Observacion.registrar({idObservacion:"OBS1",codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP999",latitud:-34,longitud:-58,comentario:"detalle"},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora);QA_Assert.error(()=>BLL_Observacion.editar(o.IdObservacion,{Comentario:""},"SUP002",{supervisiones:d.supervisiones,observaciones:d.obs,tipificaciones:d.tips},ahora),"COMENTARIO_REQUERIDO");});
  q.caso("CU01-16","Eliminar observación inactiva también sus evidencias",()=>{const d=deps(),evid=new QA_Repo();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);const o=BLL_Observacion.registrar({idObservacion:"OBS1",codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP001",latitud:-34,longitud:-58},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora);evid.insertar(MAP_Evidencia.BEaFila(new BE_Evidencia("EVI1",o.IdObservacion,"FOTO","x.jpg","FILE1",ahora,Config.ESTADOS_REGISTRO.ACTIVA)));BLL_Observacion.eliminar(o.IdObservacion,"SUP002",{supervisiones:d.supervisiones,observaciones:d.obs,evidencias:evid},ahora);QA_Assert.igual(evid.rows[0][6],Config.ESTADOS_REGISTRO.ELIMINADA);});
  q.caso("CU01-17","Referencia manual reemplaza coordenadas y conserva trazabilidad",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);const o=BLL_Observacion.registrar({idObservacion:"OBS1",codigoObra:"AD566AF",codUsuario:"SUP001",idTipificacion:"TIP001",latitud:-34,longitud:-58},true,{supervisiones:d.supervisiones,tipificaciones:d.tips,observaciones:d.obs},ahora);const e=BLL_Observacion.editar(o.IdObservacion,{Latitud:null,Longitud:null,ReferenciaUbicacion:"PRUEBA 1234"},"SUP002",{supervisiones:d.supervisiones,observaciones:d.obs,tipificaciones:d.tips},ahora);QA_Assert.igual(e.Latitud,null);QA_Assert.igual(e.Longitud,null);QA_Assert.igual(e.ReferenciaUbicacion,"PRUEBA 1234");QA_Assert.igual(e.CodUsuarioUltModificacion,"SUP002");});
  q.caso("CU01-18","Finalización registra fecha y usuario finalizador",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);const fin=new Date("2026-08-20T12:30:00Z");const s=BLL_Supervision.finalizar("AD566AF","SUP002",true,d.supervisiones,fin);QA_Assert.igual(s.CodUsuarioFinalizacion,"SUP002");QA_Assert.igual(new Date(s.FechaFinalizacion).getTime(),fin.getTime());});
  q.caso("CU01-19","No permite finalizar dos veces",()=>{const d=deps();BLL_Supervision.iniciar("AD566AF","SUP001",true,{obras:d.obras,supervisiones:d.supervisiones},ahora);BLL_Supervision.finalizar("AD566AF","SUP001",true,d.supervisiones,ahora);QA_Assert.error(()=>BLL_Supervision.finalizar("AD566AF","SUP001",true,d.supervisiones,ahora),"SUPERVISION_FINALIZADA");});
  return QA_imprimir(q.resumen());}
